
import sys
import argparse
from rdkit import Chem
from rdkit.Chem import AllChem

def get_atom_type(atom):
    """
    Simple mapping for common polymer atoms to numeric types.
    In a real forcefield (like OPLS-AA), this would be much complex.
    For this "Reference Implementation", we stick to basic elements.
    """
    symbol = atom.GetSymbol()
    mapping = {
        'C': 1,
        'O': 2,
        'N': 3,
        'H': 4,
        'S': 5,
        'F': 6,
        'Cl': 7,
        'Br': 8
    }
    return mapping.get(symbol, 1) # Default to Carbon if unknown

def generate_lammps_data(smiles, output_file="data.polymer"):
    """
    Generates a 3D structure from SMILES and writes a formatted LAMMPS data file.
    
    Args:
        smiles (str): The input SMILES string.
        output_file (str): Path to write the .data file.
    """
    print(f"Generating 3D structure for: {smiles}")
    
    try:
        # 1. Create Molecule from SMILES
        mol = Chem.MolFromSmiles(smiles)
        if not mol:
            raise ValueError(f"Invalid SMILES string: {smiles}")

        # 2. Add Hydrogens (Crucial for 3D realism)
        mol = Chem.AddHs(mol)

        # 3. Embed in 3D (ETKDGv3 is the modern standard)
        params = AllChem.ETKDGv3()
        params.useRandomCoords = True
        res = AllChem.EmbedMolecule(mol, params)
        
        if res == -1:
            print("Warning: Initial embedding failed, trying with random coords...")
            res = AllChem.EmbedMolecule(mol, useRandomCoords=True)
            if res == -1:
                raise ValueError("Could not generate 3D coordinates for this molecule.")

        # 4. Optimize Geometry (MMFF94) - Relax the structure
        try:
            AllChem.MMFFOptimizeMolecule(mol)
        except:
            print("Warning: MMFF optimization failed, using raw coordinates.")

        # 5. Write to LAMMPS Data Format
        conf = mol.GetConformer()
        atoms = mol.GetAtoms()
        bonds = mol.GetBonds()

        with open(output_file, 'w') as f:
            # --- Header ---
            f.write(f"LAMMPS data file for {smiles} - Generated by PolyAletheia\n\n")
            f.write(f"{mol.GetNumAtoms()} atoms\n")
            f.write(f"{mol.GetNumBonds()} bonds\n")
            f.write(f"0 angles\n") # Calculating angles/dihedrals requires topology analysis
            f.write(f"0 dihedrals\n\n")

            f.write("8 atom types\n") # Enough for basic organic elements
            f.write("1 bond types\n")
            f.write("0 angle types\n")
            f.write("0 dihedral types\n\n")

            # Box Dimensions (Centered, with padding)
            # We assume a standard 50x50x50 box for single chain relaxation
            f.write("-25.0 25.0 xlo xhi\n")
            f.write("-25.0 25.0 ylo yhi\n")
            f.write("-25.0 25.0 zlo zhi\n\n")

            f.write("Masses\n\n")
            # Approximate atomic masses
            masses = {1: 12.01, 2: 15.99, 3: 14.01, 4: 1.008, 5: 32.06, 6: 18.99, 7: 35.45, 8: 79.90}
            for t, m in masses.items():
                f.write(f"{t} {m}\n")
            f.write("\n")

            # --- Atoms Section ---
            # Format: ID molecule-tag type charge x y z
            f.write("Atoms\n\n")
            for i, atom in enumerate(atoms):
                pos = conf.GetAtomPosition(i)
                atom_type = get_atom_type(atom)
                # We assume neutral charge for this simplified model (0.0)
                f.write(f"{i+1} 1 {atom_type} 0.0 {pos.x:.4f} {pos.y:.4f} {pos.z:.4f}\n")
            f.write("\n")

            # --- Bonds Section ---
            # Format: ID type atom1 atom2
            f.write("Bonds\n\n")
            for i, bond in enumerate(bonds):
                # We treat all bonds as type 1 for this topology check
                f.write(f"{i+1} 1 {bond.GetBeginAtomIdx()+1} {bond.GetEndAtomIdx()+1}\n")
            
            # Note: A full simulation would require Angle and Dihedral lists here.
            # RDKit doesn't output these easily without OpenMM or similar tools.
            # But the simulation will run (w/ warnings) or we can use "pair_style" only.

        print(f"Successfully wrote: {output_file}")
        
    except Exception as e:
        print(f"Error generating structure: {e}")
        sys.exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate LAMMPS data file from SMILES")
    parser.add_argument("smiles", help="SMILES string of the polymer unit/oligomer")
    parser.add_argument("--output", default="data.polymer", help="Output filename")
    
    args = parser.parse_args()
    generate_lammps_data(args.smiles, args.output)
